# Dockerfile for React client

# Build react client
FROM node:14-slim AS builder

# Working directory be app
WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

###  Installing dependencies
RUN npm install --silent

# copy local files to app folder
COPY . .

ARG BASE_URL
ENV ATLAS_URI=${BASE_URL}

RUN npm build

## second stage
FROM caddy:2.4.3-alpine

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/build /srv

EXPOSE 80

EXPOSE 443