version: "3.3"
services:
  react-app:
    image: react-app
    restart: unless-stopped
    ports: 
      - "3000:3000"
      - "443:443"
      - "80:80"
    networks: 
      - mern-app

  api-server:
    image: api-server
    restart: unless-stopped
    env_file: ./backend/.env
    ports:  
      - "8000:8000"
    networks: 
      - mern-app

networks: 
  mern-app:
    driver: bridge
volumes: 
  mongo-data:
    driver: local